name: jump_sc
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - pandas<2.0
  - numpy
  - matplotlib
  - scikit-learn=1.1.1 # Version to allow Roshan's sklearn models to predict probabilities correctly
  - scipy=1.8.1
  - pathlib2
  - scikit-learn
  - requests
  - seaborn
  - scikit-posthocs
  - notebook
  - ipython
  - pip
  - pip:
    # For creating my python environment:
    - git+https://github.com/cytomining/pycytominer.git@8e3c28d3b81efd2c241d4c792edfefaa46698115
